### ISSUE TITLE
Issue after updating to v2.3.7 of Subscriptions

### ISSUE THREAD

**Issue by jrick1229** [Prospress/woocommerce-subscriptions-renewal-logger#2]
#### Error:
```
2018-09-25 08:19:36 UTC
unexpected shutdown: PHP Fatal error Uncaught TypeError: 
Argument 1 passed to WCS_Related_Order_Store_Cached_CPT::get_related_order_ids() must be an instance of WC_Order, integer given, 
called in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php on line 1758 and 
defined in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-related-order-store-cached-cpt.php:86 

Stack trace: 

#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php(1758): 
WCS_Related_Order_Store_Cached_CPT->get_related_order_ids(34822, 'renewal') 

#1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-subscriptions-renewal-logger-master/woocommerce-subscriptions-renewal-logger.php(219): 
WC_Subscription->get_related_orders_query(34822) 

#2 /opt/bitnami/apps/wordpress/htdocs/wp-includes/class-wp-hook.php(286): WCS_Renewal_Logger::get_subscription_last_order(Object(WC_Order), 
Object(WC_Subs in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-subscriptions/includes/data-stores/class-wcs-related-order-store-cached-cpt.php on line 86
```

#### Issue
The customer is receiving lots of failed scheduled actions since updating to v2.3.7 of Subscriptions.

**Comment by jrick1229** [comment]
@james-allan 
@thenbrent 

Received this error on a recent failed scheduled action.
The stack trace seems to point here, so I was instructed to open this issue.
If you'd like me to report this elsewhere, please let me know.

Looks to be related to this PR: https://github.com/Prospress/woocommerce-subscriptions/pull/2738

**Comment by thenbrent** [comment]
Thanks @jrick1229 this is the right place for this issue. I'd encourage that store not to be running this plugin on their live site (or at least, on their live site for longer than a few hours) though. It can impact performance and should only be used for brief periods of active monitoring.
